### PR TITLE
Match gRPC socket path in Kubelet

### PR DESCRIPTION
**Pull request by ScorpioCPH**
This PR use `MountPath` which matched Kubelet

@vishh @mindprince PTAL. Thanks!

### CODE REVIEW

**Comment by mindprince** [comment]
This path is the path inside the container, it points to the correct path on the host.

https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/device-plugins/nvidia-gpu/daemonset.yaml#L32-L34
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/device-plugins/nvidia-gpu/daemonset.yaml#L52-L53

**Comment by ScorpioCPH** [comment]
@mindprince Hi, thanks for your reply, but how to deploy this by binary?
I test this on local without container, this path is not work.

**Comment by mindprince** [comment]
If you want to run this directly without a container, maybe symlink `/device-plugins` to `/var/lib/kubelet/device-plugins`?

**Comment by ScorpioCPH** [comment]
ok, sgtm.

**Pull request closed without merging**
