### PR TITLE
Add kustomization.yaml for cos

### PR DESCRIPTION
**Pull request by JohnPaton**
This will allow users to include this daemonset in their downstream builds by using
```yaml
resources:
- http://github.com/GoogleCloudPlatform/container-engine-accelerators.git//nvidia-driver-installer/cos/
```
in their own `kustomization.yaml` files

### CODE REVIEW

**Comment by JohnPaton** [comment]
Pinging @chardch :)

**Comment by chardch** [comment]
Thanks for the change @JohnPaton! Have you tested this on all supported GKE versions that support kustomization and the ones that don't?

**Comment by JohnPaton** [comment]
Hi @chardch, kustomize is independent of GKE, it's just a tool that allows for the combination and patching of kubernetes manifests (like templating, but better). This will just allow users of kustomize to include this resource in their own manifests, and to patch it as needed (if desired).

**Comment by JohnPaton** [comment]
@chardch is that clear enough?

**Review by pradvenkat — APPROVED** [review]
Thanks for the PR.

**Pull request merged**
