### PR TITLE
include xorg drivers

### PR DESCRIPTION
**Pull request by lsjostro**
xorg drivers is needed for remote rendering.

### CODE REVIEW

**Comment by mindprince** [comment]
GKE officially supports installation of NVIDIA GPU drivers on Ubuntu now. The instructions to use that are here: https://cloud.google.com/kubernetes-engine/docs/how-to/gpus#installing_drivers

The officially supported version doesn't use this entrypoint.sh file (but uses a script present on the node image itself).

cc - @yguo0905 @jiayingz @vishh if it makes sense to add this to our official installation.

**Comment by lsjostro** [comment]
yeah, and it doesn't include the X drivers unfortunately. Is the install script open sourced somewhere?
otherwise we need to roll our own.

**Comment by vishh** [comment]
@yguo0905 can we get Canonical to include this change in their driver installer?

@mindprince if the Ubuntu installer is this repo is being widely used, we can accept this patch with a caveat that we do not intend to maintain it.

**Comment by lsjostro** [comment]
here is the ubuntu nvidia deb package content (as you can see no xorg drivers included)
https://gist.github.com/lsjostro/7d2a468bcd7eca2865646f333517217a

**Comment by lsjostro** [comment]
Canonical should btw open source their stuff? ;-)

**Comment by jiayingz** [comment]
@lsjostro I saw you also updated the driver version. Is this to support the latest Cuda API?
Do you have a workload container that we may use for testing so that next time when we update the driver version again, we may run it to verify xorg applications still work?

**Comment by lsjostro** [comment]
@jiayingz Sure, I'll publish a test example! And yes we need CUDA 10.

**Comment by lsjostro** [comment]
@jiayingz https://github.com/EmbarkStudios/gke-accelerated-xorg-example
Test deployment manifest:
https://github.com/EmbarkStudios/gke-accelerated-xorg-example/blob/master/deployment.yaml

**Comment by lsjostro** [comment]
any more thoughts on this?

**Comment by jiayingz** [comment]
@lsjostro thanks a lot for the example test. Would your test work with the daemonset.yaml included in this directory? I manually built a ubuntu-nvidia-driver-installer with your patch applied and then run it with the latest ubuntu gke image. The driver installation finished successfully but when I launched your test deployment, it soon entered crashloop. Other than the changes included in this PR, do we also need any additional set up in the installer daemonset or any other configurations?

**Comment by lsjostro** [comment]
@jiayingz The daemonset is exactly the same except for installer image from this PR.
But I'll try to reproduce. I'll get back to you.

**Comment by bhack** [comment]
You can render headless with EGL and without GLX. 
https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#is-opengl-supported

**Comment by lsjostro** [comment]
I wish! Unity does not support EGL that I know unfortunately. 😩

**Comment by bhack** [comment]
@lsjostro So these flags are still requiring GLX? https://answers.unity.com/questions/1488461/are-headless-batchmode-nographics-available-in-uni.html

**Comment by lsjostro** [comment]
I believe so.. but I'm no unity Expert. I will double check with team. Cheers anyways.

**Comment by potitoaghilar** [comment]
Is this still up? The result is a CrashLoopBack of xorg container due to no file found in path /dev/dri/card0. It seems GPUs are not accessible in this path

**Comment by lsjostro** [comment]
Probably can close this now.

**Pull request closed without merging**
