### PR TITLE
Add nvidia-driver-installer for ubuntu that works the same way as the one for COS.

### PR DESCRIPTION
**Pull request by mindprince**
Tested it on the upcoming ubuntu image for GKE 1.9

### CODE REVIEW

**Comment by mindprince** [comment]
Also, here's the diff between the new cos entrypoint.sh and ubuntu's entrypoint.sh: https://gist.github.com/anonymous/fc89e481d9529cfe5744d4b3a19df64c

**Comment by vishh** [comment]
This looks good to me, but I'd prefer having someone from Canonical review this. Perhaps @yguo0905 can help with this.

**Comment by mindprince** [comment]
Also, @cmluciano was interested in Ubuntu support IIRC. Maybe he can also test it.

(I have tested it on an yet unreleased ubuntu image that will be used with GKE 1.9)

**Comment by yguo0905** [comment]
If we need a formal review, we should create an internal ticket to explain what we do and ask someone from Canonical to take a look.

**Comment by cmluciano** [comment]
Excellent! I will try this out.

**Comment by mindprince** [comment]
@cmluciano Note that this is just the driver installer. After this, you would have to run https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/device-plugins/nvidia-gpu/daemonset.yaml for the device plugin.

**Pull request merged**
