### PR TITLE
Report NUMA node for use by k8s TopologyManager

### PR DESCRIPTION
**Pull request by robertdavidsmith**
This PR makes the device plugin report GPU NUMA node for use by K8s TopologyManager.

First it uses NVML to map device id to pci bus id. Then it uses the pci bus id to find the relevant numa_node file under /sys, parses this file and returns the NUMA node to k8s via protobuf.

This feature is off by default, but can be enabled via the -topology command line option.

### CODE REVIEW

**Comment by robertdavidsmith** [comment]
@googlebot I signed it!

**Comment by ruiwen-zhao** [comment]
Hi @robertdavidsmith thanks for the PR! Can we combine those commits into one? Also, looks like you are still working on it, and if so can you mark this PR as WIP by converting it to a draft?

**Comment by robertdavidsmith** [comment]
> Hi @robertdavidsmith thanks for the PR! Can we combine those commits into one? Also, looks like you are still working on it, and if so can you mark this PR as WIP by converting it to a draft?

Hi,

I've now finished working on it, it's ready to be reviewed.

Is a squash and merged once reviewed sufficient, or do you want me to rebase or squash into a new branch?

**Comment by ruiwen-zhao** [comment]
> > Hi @robertdavidsmith thanks for the PR! Can we combine those commits into one? Also, looks like you are still working on it, and if so can you mark this PR as WIP by converting it to a draft?
> 
> Hi,
> 
> I've now finished working on it, it's ready to be reviewed.
> 
> Is a squash and merge once reviewed sufficient, or do you want me to squash into a new branch?

Just want to keep the commit msg clean and make it easier to review. So can you squash them into one commit if your work is done?

**Comment by robertdavidsmith** [comment]
> > > Hi @robertdavidsmith thanks for the PR! Can we combine those commits into one? Also, looks like you are still working on it, and if so can you mark this PR as WIP by converting it to a draft?
> > 
> > 
> > Hi,
> > I've now finished working on it, it's ready to be reviewed.
> > Is a squash and merge once reviewed sufficient, or do you want me to squash into a new branch?
> 
> Just want to keep the commit msg clean and make it easier to review. So can you squash them into one commit if your work is done?

Making a new PR now hang on

**Comment by robertdavidsmith** [comment]
> > > > Hi @robertdavidsmith thanks for the PR! Can we combine those commits into one? Also, looks like you are still working on it, and if so can you mark this PR as WIP by converting it to a draft?
> > > 
> > > 
> > > Hi,
> > > I've now finished working on it, it's ready to be reviewed.
> > > Is a squash and merge once reviewed sufficient, or do you want me to squash into a new branch?
> > 
> > 
> > Just want to keep the commit msg clean and make it easier to review. So can you squash them into one commit if your work is done?
> 
> Making a new PR now hang on

made https://github.com/GoogleCloudPlatform/container-engine-accelerators/pull/167

**Pull request closed without merging**
