### PR TITLE
Add nvidia-driver-installer for CoreOS Container Linux

### PR DESCRIPTION
**Pull request by lsjostro**
This PR adds nvidia driver installer for CoreOS Container Linux.

### CODE REVIEW

**Comment by lsjostro** [comment]
I signed it!

**Comment by discordianfish** [comment]
@lsjostro I'm trying this out right now. This only addresses the driver parts though, right? It's doesn't seem to install the libnvidia-container nor nvidia-container-runtime, correct?

**Comment by lsjostro** [comment]
@discordianfish correct.  We are using googles own [nvidia k8s device plugin](https://raw.githubusercontent.com/kubernetes/kubernetes/release-1.9/cluster/addons/device-plugins/nvidia-gpu/daemonset.yaml) instead of the official nvidia plugin, which doesn't require a custom docker runtime. Works really well for us.

Currently we have coreos nvidia installer Dockerfile hosted [here](https://github.com/shelmangroup/coreos-gpu-installer) and docker image [here](https://hub.docker.com/r/shelmangroup/coreos-nvidia-driver-installer/)

**Comment by discordianfish** [comment]
@lsjostro Ah thanks for that hint! So this installer container and the k8s device plugin should be enough?

I thought it's needed since my pods still fail to schedule (Insufficient nvidia.com/gpu). I'm using the same k8s device plugin manifest. Guess I've been down the wrong route.

When dropping the `nvidia.com/gpu: 1` limit, the [test pod](https://gist.github.com/discordianfish/9ac14ec94f13bd3c7cc42c94482b04a6) gets scheduled but fails with:

```
libdc1394 error: Failed to initialize libdc1394
..
cudaRuntimeGetVersion() failed with error #35
```

The k8s plugin is running fine though:
```
I0213 10:52:04.891238    1412 nvidia_gpu.go:258] device-plugin started
I0213 10:53:35.096858    1412 nvidia_gpu.go:82] Found Nvidia GPU "nvidia0"
I0213 10:53:35.096935    1412 nvidia_gpu.go:209] starting device-plugin server at: /device-plugin/nvidiaGPU-1518519215.sock
I0213 10:53:35.097257    1412 nvidia_gpu.go:231] device-plugin server started serving
I0213 10:53:35.098269    1412 nvidia_gpu.go:240] device-plugin registered with the kubelet
I0213 10:53:35.098918    1412 nvidia_gpu.go:143] device-plugin: ListAndWatch start
I0213 10:53:35.098948    1412 nvidia_gpu.go:159] ListAndWatch: send devices &ListAndWatchResponse{Devices:[&Device{ID:nvidia0,Health:Healthy,}],}
```

Well, guess I have to dig deeper. Looks like the installer worked fine. Thanks a lot for that!

**Comment by discordianfish** [comment]
I think with the approach of bind-mounting the shared libs from the host, once has to run ldconfig to update the ld cache before starting an application. The official digits container isn't doing that.

**Comment by lsjostro** [comment]
make sure you add `-host-path=/opt/nvidia` to the k8s device plugin cmdline.

**Comment by discordianfish** [comment]
Yep, figured that out. Maybe the default should be changed, /home/kubernetes is an odd choice.

**Comment by vishh** [comment]
I'd recommend having a single daemonset perform driver installation and run the device plugin and that way sharing driver artifacts are controlled via a single config file. 

On the other hand, we at Google do not have bandwidth to setup CI and maintain installations for additional OSes. I would like to not merge this until we identify a maintenance plan.

**Comment by lsjostro** [comment]
@vishh thanks for the feedback! I totally understand that! We’ll host it here in the meanwhile https://github.com/shelmangroup/coreos-gpu-installer

**Comment by amoghkashyap** [comment]
@lsjostro Thanks for the patch. Nvidia-drivers are installed on the V100. However, I am having difficulty in getting the runtime set to NVIDIA. Because of this, I am not able to run nvidia-docker or use the nvidia-smi inside the Kubernetes pod which needs GPU acceleration. Request you to help me out.

CoreOS version : 2079.3.0

Also, I guess the docker tag has to be used as "master" in the daemonset.yml since "latest" is not being pulled.

**Comment by lsjostro** [comment]
@amoghkashyap sure! mind coping the issue to https://github.com/shelmangroup/coreos-gpu-installer ?

**Pull request closed without merging**
